- class: prexsyn.properties.fingerprint.ECFP4
  params:
    name: ecfp4
- class: prexsyn.properties.fingerprint.FCFP4
  params:
    name: fcfp4
- class: prexsyn.properties.rdkit_descriptors.RDKitDescriptors
  params:
    name: rdkit_descriptors
    num_evaluated_descriptors: 4
- class: prexsyn.properties.rdkit_descriptors.RDKitDescriptorUpperBound
  params:
    name: rdkit_descriptor_upper_bound
- class: prexsyn.properties.brics.BRICSFragments
  params:
    name: brics
    max_num_fragments: 8
